core_server:
  core_url: http://localhost:8080
  grpc_addr: localhost:9090

missions:
  - id: to_kitchen
    key: key_to_kitchen
  - id: from_kitchen
    key: key_from_kitchen

app:
  name: AV Delivery App
  http_port: 8082

from_kitchen:
  vehicle_id: vehicle-01
  gate_id: gate-01
  kitchen_robot_id: robot-kitchen-01
  institution_robot_id: robot-institution-01
  lift_id: lift-01
